"""
PolicyPilot - Government Schemes Database
40 schemes across 4 categories: Education, Employment, Health, Agriculture
"""

SCHEMES = [
    # ===== EDUCATION (10) =====
    {
        "id": "nsp",
        "name": "National Scholarship Portal (NSP)",
        "nameHi": "राष्ट्रीय छात्रवृत्ति पोर्टल (NSP)",
        "category": "Education",
        "state": "Central",
        "keywords": ["student", "scholarship", "college", "education", "university", "छात्र", "छात्रवृत्ति"],
        "eligibility": "Students with family income below specified thresholds in recognized institutions",
        "citation": "NSP Guidelines: 'All students pursuing education in recognized institutions with family income below specified thresholds are eligible for various central and state scholarships.'",
        "benefits": "Multiple scholarships from ₹5,000 to ₹50,000 per year",
        "reasoningHi": "छात्र के रूप में, आप NSP के माध्यम से कई छात्रवृत्तियों का लाभ उठा सकते हैं।",
        "documents": ["Aadhaar Card", "Income Certificate", "Previous Marksheet", "Bank Account", "Institution ID"],
        "steps": ["Register on scholarships.gov.in", "Fill application for relevant schemes", "Upload documents", "Institute verification → Disbursement"],
        "deadline": "October-November each year",
        "link": "https://scholarships.gov.in"
    },
    {
        "id": "css-college",
        "name": "Central Sector Scheme of Scholarship for College Students",
        "nameHi": "कॉलेज छात्रों के लिए केंद्रीय क्षेत्र छात्रवृत्ति",
        "category": "Education",
        "state": "Central",
        "keywords": ["student", "college", "merit", "scholarship", "graduation", "छात्र"],
        "eligibility": "Top 20th percentile of board exam, family income below ₹8,00,000",
        "citation": "Ministry of Education: 'Students in top 20th percentile of board exam, family income below ₹8,00,000, are eligible.'",
        "benefits": "₹10,000/yr (UG) to ₹20,000/yr (PG)",
        "reasoningHi": "मेरिट-आधारित छात्रवृत्ति, आय ₹8 लाख से कम वाले परिवारों के लिए।",
        "documents": ["Board Marksheet", "Income Certificate", "College Admission Letter", "Aadhaar", "Bank Account"],
        "steps": ["Apply through NSP", "Submit marks and income proof", "College verification", "Direct bank transfer"],
        "deadline": "October 31 each year",
        "link": "https://scholarships.gov.in"
    },
    {
        "id": "nmmss",
        "name": "National Means-cum-Merit Scholarship (NMMSS)",
        "nameHi": "राष्ट्रीय साधन-सह-योग्यता छात्रवृत्ति (NMMSS)",
        "category": "Education",
        "state": "Central",
        "keywords": ["student", "school", "class 9", "merit", "scholarship", "छात्र"],
        "eligibility": "Class 8 students with 55%+ marks, family income below ₹3,50,000",
        "citation": "DSEL: 'Students of class 9-12 studying in government schools with parental income below ₹3,50,000 are eligible.'",
        "benefits": "₹12,000 per year for 4 years (Class 9-12)",
        "reasoningHi": "सरकारी स्कूल के छात्रों के लिए मेरिट छात्रवृत्ति।",
        "documents": ["School ID", "Class 8 Marksheet", "Income Certificate", "Aadhaar", "Bank Account"],
        "steps": ["Apply through school", "Appear for selection test", "Merit list published", "Scholarship disbursed via NSP"],
        "deadline": "Check state notification",
        "link": "https://dsel.education.gov.in"
    },
    {
        "id": "pragati",
        "name": "AICTE Pragati Scholarship for Girl Students",
        "nameHi": "AICTE प्रगति छात्रवृत्ति (लड़कियों के लिए)",
        "category": "Education",
        "state": "Central",
        "keywords": ["girl", "female", "engineering", "technical", "diploma", "student", "women", "लड़की", "महिला"],
        "eligibility": "Girl students in AICTE-approved technical degree/diploma, family income below ₹8 lakh",
        "citation": "AICTE Pragati: 'One girl per family in AICTE-approved institution, family income below ₹8,00,000.'",
        "benefits": "₹50,000 per year (tuition fee waiver + incidental charges)",
        "reasoningHi": "तकनीकी शिक्षा में लड़कियों के लिए AICTE छात्रवृत्ति।",
        "documents": ["Aadhaar", "Admission Letter", "Income Certificate", "10th/12th Marksheet"],
        "steps": ["Apply on NSP during open window", "Upload documents", "Institute verification", "Amount credited to account"],
        "deadline": "November each year",
        "link": "https://scholarships.gov.in"
    },
    {
        "id": "saksham",
        "name": "AICTE Saksham Scholarship for Specially Abled Students",
        "nameHi": "AICTE सक्षम छात्रवृत्ति (दिव्यांग छात्रों के लिए)",
        "category": "Education",
        "state": "Central",
        "keywords": ["disabled", "specially abled", "handicapped", "technical", "student", "दिव्यांग"],
        "eligibility": "Specially abled students with 40%+ disability in AICTE-approved institutions",
        "citation": "AICTE Saksham: 'Students with 40%+ disability in AICTE institutions, family income below ₹8 lakh.'",
        "benefits": "₹50,000 per year",
        "reasoningHi": "दिव्यांग छात्रों के लिए AICTE छात्रवृत्ति।",
        "documents": ["Disability Certificate", "Aadhaar", "Income Certificate", "Admission Letter"],
        "steps": ["Apply on NSP", "Upload disability certificate", "Verification", "Disbursement"],
        "deadline": "November each year",
        "link": "https://scholarships.gov.in"
    },
    {
        "id": "swanath",
        "name": "AICTE Swanath Scholarship",
        "nameHi": "AICTE स्वनाथ छात्रवृत्ति",
        "category": "Education",
        "state": "Central",
        "keywords": ["orphan", "student", "technical", "single parent", "अनाथ"],
        "eligibility": "Orphans, wards of COVID victims, single-parent children in technical education",
        "citation": "AICTE Swanath: 'Orphans and wards of parents who died due to COVID in AICTE institutions.'",
        "benefits": "₹50,000 per year",
        "reasoningHi": "अनाथ और COVID प्रभावित परिवारों के बच्चों के लिए छात्रवृत्ति।",
        "documents": ["Death Certificate of Parents", "Aadhaar", "Admission Letter", "Income Certificate"],
        "steps": ["Apply on NSP", "Submit death/COVID certificates", "Verification", "Disbursement"],
        "deadline": "November each year",
        "link": "https://scholarships.gov.in"
    },
    {
        "id": "pm-usp-jk",
        "name": "PM-USP Scholarship for J&K and Ladakh",
        "nameHi": "PM-USP छात्रवृत्ति (J&K और लद्दाख)",
        "category": "Education",
        "state": "Central",
        "keywords": ["kashmir", "ladakh", "student", "scholarship", "jammu"],
        "eligibility": "Students from J&K and Ladakh pursuing higher education",
        "citation": "PM-USP: 'Students domiciled in J&K/Ladakh in recognized institutions are eligible.'",
        "benefits": "Up to ₹3,00,000 per year (maintenance + tuition)",
        "reasoningHi": "जम्मू-कश्मीर और लद्दाख के छात्रों के लिए विशेष छात्रवृत्ति।",
        "documents": ["Domicile Certificate", "Aadhaar", "Admission Letter", "Income Certificate"],
        "steps": ["Apply on NSP", "Upload domicile proof", "Verification", "Disbursement"],
        "deadline": "October each year",
        "link": "https://scholarships.gov.in"
    },
    {
        "id": "pg-scholarship",
        "name": "National Scholarship for Post Graduate Studies",
        "nameHi": "स्नातकोत्तर अध्ययन के लिए राष्ट्रीय छात्रवृत्ति",
        "category": "Education",
        "state": "Central",
        "keywords": ["postgraduate", "masters", "pg", "student", "university", "research"],
        "eligibility": "PG students in UGC-recognized universities with merit",
        "citation": "UGC: 'Meritorious students pursuing PG in UGC-recognized universities are eligible.'",
        "benefits": "₹3,100 per month for 2 years",
        "reasoningHi": "UGC मान्यता प्राप्त विश्वविद्यालयों में PG छात्रों के लिए।",
        "documents": ["UG Degree", "PG Admission Letter", "Aadhaar", "Bank Account"],
        "steps": ["Apply via NSP", "Submit academic records", "University verification", "Monthly stipend credited"],
        "deadline": "As per UGC notification",
        "link": "https://scholarships.gov.in"
    },
    {
        "id": "ishan-uday",
        "name": "Ishan Uday Scholarship for NER",
        "nameHi": "ईशान उदय छात्रवृत्ति (पूर्वोत्तर)",
        "category": "Education",
        "state": "Central",
        "keywords": ["northeast", "NER", "student", "scholarship", "assam", "manipur", "meghalaya"],
        "eligibility": "Students from 8 NE states pursuing higher education outside NER",
        "citation": "UGC Ishan Uday: 'Students from NE states studying outside the region in recognized institutions.'",
        "benefits": "₹5,400/month (Professional) or ₹3,800/month (Non-professional)",
        "reasoningHi": "पूर्वोत्तर क्षेत्र के छात्रों के लिए विशेष छात्रवृत्ति।",
        "documents": ["Domicile Certificate (NE State)", "Aadhaar", "Admission Letter", "Bank Account"],
        "steps": ["Apply on NSP", "Upload NE domicile proof", "Verification", "Monthly stipend"],
        "deadline": "October each year",
        "link": "https://scholarships.gov.in"
    },
    {
        "id": "sc-topclass",
        "name": "Top Class Education Scheme for SC Students",
        "nameHi": "अनुसूचित जाति छात्रों के लिए उच्च शिक्षा योजना",
        "category": "Education",
        "state": "Central",
        "keywords": ["SC", "scheduled caste", "student", "scholarship", "dalit", "अनुसूचित जाति"],
        "eligibility": "SC students in top institutions, family income below ₹6 lakh",
        "citation": "Ministry of Social Justice: 'SC students admitted to top-class institutions with income below ₹6 lakh.'",
        "benefits": "Full tuition + living expenses up to ₹2,20,000/year",
        "reasoningHi": "प्रमुख संस्थानों में SC छात्रों के लिए पूर्ण शुल्क + रहने का खर्च।",
        "documents": ["Caste Certificate", "Income Certificate", "Aadhaar", "Admission Letter"],
        "steps": ["Apply on NSP", "Submit caste and income certificates", "Institute verification", "Full support credited"],
        "deadline": "As per NSP calendar",
        "link": "https://scholarships.gov.in"
    },

    # ===== EMPLOYMENT (10) =====
    {
        "id": "mgnrega",
        "name": "MGNREGA",
        "nameHi": "मनरेगा (MGNREGA)",
        "category": "Employment",
        "state": "Central",
        "keywords": ["job", "employment", "rural", "work", "wage", "labour", "unskilled", "रोज़गार", "काम", "मज़दूर"],
        "eligibility": "All rural households, adult members willing to do unskilled manual work",
        "citation": "MGNREGA Act 2005, Section 3(1): 'Every rural household whose adult members volunteer for unskilled manual work.'",
        "benefits": "100 days guaranteed wage employment, ₹250-350/day",
        "reasoningHi": "हर ग्रामीण परिवार को 100 दिन वेतन रोजगार की गारंटी।",
        "documents": ["Aadhaar Card", "Job Card", "Bank Account"],
        "steps": ["Apply for Job Card at Gram Panchayat", "Submit written work application", "Work provided within 15 days", "Wages in bank within 15 days"],
        "deadline": "Anytime — demand-driven",
        "link": "https://mnregaweb2.nic.in"
    },
    {
        "id": "ddu-gky",
        "name": "DDU-GKY (Grameen Kaushalya Yojana)",
        "nameHi": "DDU-GKY (ग्रामीण कौशल्य योजना)",
        "category": "Employment",
        "state": "Central",
        "keywords": ["skill", "training", "rural", "youth", "job", "employment", "कौशल", "प्रशिक्षण"],
        "eligibility": "Rural youth aged 15-35, BPL families",
        "citation": "DDU-GKY Guidelines: 'Rural youth aged 15-35 from BPL families are eligible for free skill training.'",
        "benefits": "Free skill training + placement support + stipend",
        "reasoningHi": "ग्रामीण युवाओं के लिए मुफ्त कौशल प्रशिक्षण और नौकरी।",
        "documents": ["Aadhaar", "BPL Certificate", "Age Proof", "Bank Account"],
        "steps": ["Register at nearest DDU-GKY centre", "Choose skill trade", "Complete training", "Placement assistance"],
        "deadline": "Rolling enrollment",
        "link": "http://demo.nirdpr.org.in/DDU-GKY.html"
    },
    {
        "id": "pmkvy",
        "name": "PM Kaushal Vikas Yojana (PMKVY)",
        "nameHi": "प्रधानमंत्री कौशल विकास योजना (PMKVY)",
        "category": "Employment",
        "state": "Central",
        "keywords": ["skill", "training", "youth", "certification", "job", "कौशल", "प्रशिक्षण", "युवा"],
        "eligibility": "Indian nationals aged 15-45 not in formal employment",
        "citation": "PMKVY 4.0: 'Indian nationals aged 15-45 who seek skill certification are eligible.'",
        "benefits": "Free training + ₹8,000 reward + placement support",
        "reasoningHi": "युवाओं के लिए मुफ्त कौशल विकास + प्रमाणन + प्लेसमेंट।",
        "documents": ["Aadhaar", "Education Certificate", "Bank Account"],
        "steps": ["Find centre at pmkvyofficial.org", "Enroll in skill course", "Complete 3-6 month training", "Get certified + placement"],
        "deadline": "Rolling enrollment",
        "link": "https://www.pmkvyofficial.org"
    },
    {
        "id": "pmegp",
        "name": "PM Employment Generation Programme (PMEGP)",
        "nameHi": "प्रधानमंत्री रोज़गार सृजन कार्यक्रम (PMEGP)",
        "category": "Employment",
        "state": "Central",
        "keywords": ["self-employment", "entrepreneur", "business", "startup", "loan", "उद्यम", "व्यापार"],
        "eligibility": "Individuals above 18 years, project cost up to ₹50 lakh (manufacturing)",
        "citation": "PMEGP: 'Any individual above 18 years with 8th pass for projects above ₹10 lakh.'",
        "benefits": "Subsidy 25-35% on project cost up to ₹50 lakh",
        "reasoningHi": "स्व-रोज़गार के लिए ₹50 लाख तक की परियोजना पर 25-35% सब्सिडी।",
        "documents": ["Aadhaar", "Education Certificate", "Project Report", "Caste Certificate (if applicable)"],
        "steps": ["Apply online at kviconline.gov.in", "Submit project report", "Bank interview", "Subsidy credited after disbursement"],
        "deadline": "Year-round",
        "link": "https://www.kviconline.gov.in"
    },
    {
        "id": "pm-svanidhi",
        "name": "PM SVANidhi (Street Vendors)",
        "nameHi": "PM स्वनिधि (स्ट्रीट वेंडर्स)",
        "category": "Employment",
        "state": "Central",
        "keywords": ["vendor", "street", "hawker", "small business", "loan", "दुकानदार"],
        "eligibility": "Street vendors with vending certificate/letter of recommendation",
        "citation": "PM SVANidhi: 'Street vendors with certificate from ULB or recommendation letter are eligible.'",
        "benefits": "₹10,000 to ₹50,000 micro-loans with 7% interest subsidy",
        "reasoningHi": "स्ट्रीट वेंडर्स को ₹10,000-50,000 का ऋण, 7% ब्याज सब्सिडी के साथ।",
        "documents": ["Vending Certificate/LoR", "Aadhaar", "Bank Account"],
        "steps": ["Apply at pmsvanidhi.mohua.gov.in", "Submit vending certificate", "Bank verification", "Loan disbursed"],
        "deadline": "Ongoing",
        "link": "https://pmsvanidhi.mohua.gov.in"
    },
    {
        "id": "ncs",
        "name": "National Career Service (NCS)",
        "nameHi": "राष्ट्रीय करियर सेवा (NCS)",
        "category": "Employment",
        "state": "Central",
        "keywords": ["job", "career", "placement", "employment", "naukri", "नौकरी"],
        "eligibility": "Any Indian job seeker",
        "citation": "NCS Portal: 'Free registration for all Indian job seekers and employers.'",
        "benefits": "Free job matching + career counselling + skill training links",
        "reasoningHi": "मुफ्त नौकरी खोज, करियर परामर्श और कौशल प्रशिक्षण।",
        "documents": ["Aadhaar", "Resume/CV"],
        "steps": ["Register at ncs.gov.in", "Upload resume", "Browse jobs", "Apply directly"],
        "deadline": "Always open",
        "link": "https://www.ncs.gov.in"
    },
    {
        "id": "nai-manzil",
        "name": "Nai Manzil Scheme",
        "nameHi": "नई मंज़िल योजना",
        "category": "Employment",
        "state": "Central",
        "keywords": ["minority", "madrasa", "education", "skill", "muslim", "अल्पसंख्यक"],
        "eligibility": "Minority youth aged 17-35 who are school dropouts",
        "citation": "Nai Manzil: 'Minority community youth aged 17-35 who dropped out of formal education.'",
        "benefits": "Bridge course + skill training + ₹1,500/month stipend",
        "reasoningHi": "अल्पसंख्यक युवाओं के लिए शिक्षा + कौशल प्रशिक्षण।",
        "documents": ["Minority Certificate", "Aadhaar", "Age Proof"],
        "steps": ["Contact nearest training centre", "Enroll in bridge education", "Complete skill module", "Placement support"],
        "deadline": "Ongoing",
        "link": "https://www.minorityaffairs.gov.in"
    },
    {
        "id": "seekho-kamao",
        "name": "Seekho aur Kamao (Learn and Earn)",
        "nameHi": "सीखो और कमाओ",
        "category": "Employment",
        "state": "Central",
        "keywords": ["minority", "skill", "learn", "earn", "training", "craft", "अल्पसंख्यक"],
        "eligibility": "Minority youth aged 14-35, minimum 5th pass",
        "citation": "Seekho aur Kamao: 'Minority youth aged 14-35, minimum 5th pass, for traditional skill training.'",
        "benefits": "Free skill training in traditional crafts + stipend",
        "reasoningHi": "पारंपरिक शिल्प में मुफ्त प्रशिक्षण + वजीफा।",
        "documents": ["Minority Certificate", "Aadhaar", "Education Certificate"],
        "steps": ["Apply at minorityaffairs.gov.in", "Select trade", "Complete training", "Certification + placement"],
        "deadline": "Ongoing",
        "link": "https://www.minorityaffairs.gov.in"
    },
    {
        "id": "garib-kalyan",
        "name": "Garib Kalyan Rozgar Yojana",
        "nameHi": "गरीब कल्याण रोज़गार योजना",
        "category": "Employment",
        "state": "Central",
        "keywords": ["migrant", "rural", "employment", "covid", "work", "प्रवासी", "मज़दूर"],
        "eligibility": "Returnee migrant workers in rural areas",
        "citation": "GKRY 2020: 'Returnee migrant workers and rural citizens affected by COVID lockdowns.'",
        "benefits": "Employment in 25 infrastructure projects + wages",
        "reasoningHi": "लौटे प्रवासी श्रमिकों और ग्रामीण नागरिकों को रोज़गार।",
        "documents": ["Aadhaar", "MGNREGA Job Card", "Bank Account"],
        "steps": ["Register at Gram Panchayat", "Enroll in available projects", "Work and receive wages"],
        "deadline": "As per state notification",
        "link": "https://pib.gov.in"
    },
    {
        "id": "labour-welfare",
        "name": "Labour Welfare Scheme (Education)",
        "nameHi": "श्रम कल्याण योजना (शिक्षा)",
        "category": "Employment",
        "state": "Central",
        "keywords": ["labour", "worker", "children", "education", "factory", "श्रमिक"],
        "eligibility": "Children of workers in establishments covered under Labour Welfare Fund",
        "citation": "Labour Welfare Fund Act: 'Children of registered workers are eligible for education assistance.'",
        "benefits": "Education assistance for workers' children",
        "reasoningHi": "पंजीकृत श्रमिकों के बच्चों को शिक्षा सहायता।",
        "documents": ["Worker ID Card", "Aadhaar", "Child's School Certificate"],
        "steps": ["Apply through employer", "Submit worker registration", "Verification", "Assistance provided"],
        "deadline": "As per state calendar",
        "link": "https://labour.gov.in"
    },

    # ===== HEALTH (10) =====
    {
        "id": "pmjay",
        "name": "Ayushman Bharat PM-JAY",
        "nameHi": "आयुष्मान भारत पीएम-जय",
        "category": "Health",
        "state": "Central",
        "keywords": ["health", "hospital", "medical", "insurance", "treatment", "surgery", "स्वास्थ्य", "अस्पताल", "इलाज"],
        "eligibility": "Families in SECC 2011 data or income below ₹5,00,000",
        "citation": "AB PM-JAY: 'All families identified in SECC 2011 or with income below ₹5 lakh are eligible for ₹5 lakh/year coverage.'",
        "benefits": "₹5,00,000/year health coverage per family",
        "reasoningHi": "₹5 लाख/वर्ष का मुफ्त स्वास्थ्य बीमा।",
        "documents": ["Aadhaar", "Ration Card", "SECC Letter"],
        "steps": ["Check at mera.pmjay.gov.in", "Visit empaneled hospital", "Show Aadhaar at Ayushman counter", "Cashless treatment"],
        "deadline": "No deadline — continuous",
        "link": "https://pmjay.gov.in"
    },
    {
        "id": "pm-abhim",
        "name": "PM-ABHIM (Health Infrastructure Mission)",
        "nameHi": "PM-ABHIM (स्वास्थ्य अवसंरचना मिशन)",
        "category": "Health",
        "state": "Central",
        "keywords": ["health", "infrastructure", "hospital", "clinic", "स्वास्थ्य"],
        "eligibility": "District/block-level public health infra development",
        "citation": "PM-ABHIM Notification: 'Strengthening health infrastructure at district and block levels.'",
        "benefits": "New health centres and upgraded hospitals",
        "reasoningHi": "जिला और ब्लॉक स्तर पर स्वास्थ्य अवसंरचना सुधार।",
        "documents": [],
        "steps": ["Benefits through improved local health facilities"],
        "deadline": "Ongoing infrastructure development",
        "link": "https://main.mohfw.gov.in"
    },
    {
        "id": "nhm",
        "name": "National Health Mission (NHM)",
        "nameHi": "राष्ट्रीय स्वास्थ्य मिशन (NHM)",
        "category": "Health",
        "state": "Central",
        "keywords": ["health", "maternal", "child", "pregnancy", "vaccination", "स्वास्थ्य", "गर्भवती", "टीका"],
        "eligibility": "All citizens, focus on rural and urban poor",
        "citation": "NHM Framework: 'Universal access to equitable healthcare for all, especially underserved.'",
        "benefits": "Free maternal & child care, immunization, disease treatment",
        "reasoningHi": "मुफ्त मातृ-शिशु देखभाल, टीकाकरण।",
        "documents": ["Aadhaar", "Health Card"],
        "steps": ["Visit nearest PHC/Sub-Centre", "Register for services", "Receive free treatment"],
        "deadline": "Always available",
        "link": "https://main.mohfw.gov.in"
    },
    {
        "id": "pmssy",
        "name": "PM Swasthya Suraksha Yojana (PMSSY)",
        "nameHi": "PM स्वास्थ्य सुरक्षा योजना (PMSSY)",
        "category": "Health",
        "state": "Central",
        "keywords": ["health", "AIIMS", "super speciality", "hospital", "स्वास्थ्य"],
        "eligibility": "Citizens needing super-speciality care in underserved states",
        "citation": "PMSSY: 'Establishing new AIIMS and upgrading medical colleges in underserved states.'",
        "benefits": "Access to AIIMS-quality healthcare locally",
        "reasoningHi": "कम-सुविधा वाले राज्यों में AIIMS स्तर की स्वास्थ्य सेवा।",
        "documents": ["Aadhaar", "Medical Referral"],
        "steps": ["Get referral from district hospital", "Visit new AIIMS/upgraded centre", "Receive treatment"],
        "deadline": "Ongoing",
        "link": "https://main.mohfw.gov.in"
    },
    {
        "id": "pmbjp",
        "name": "PM Bhartiya Janaushadhi Pariyojana (PMBJP)",
        "nameHi": "PM भारतीय जनऔषधि परियोजना (PMBJP)",
        "category": "Health",
        "state": "Central",
        "keywords": ["medicine", "generic", "affordable", "pharmacy", "cheap", "दवा", "सस्ती"],
        "eligibility": "All citizens — affordable generic medicines",
        "citation": "PMBJP: 'Quality generic medicines at 50-90% less cost through Janaushadhi Kendras.'",
        "benefits": "Generic medicines at 50-90% less cost",
        "reasoningHi": "जेनेरिक दवाइयाँ 50-90% कम कीमत पर।",
        "documents": ["Doctor's Prescription"],
        "steps": ["Find nearest Janaushadhi Kendra", "Show prescription", "Buy generic medicines at low cost"],
        "deadline": "Always available",
        "link": "https://janaushadhi.gov.in"
    },
    {
        "id": "abdm",
        "name": "Ayushman Bharat Digital Mission (ABDM)",
        "nameHi": "आयुष्मान भारत डिजिटल मिशन (ABDM)",
        "category": "Health",
        "state": "Central",
        "keywords": ["digital", "health", "ABHA", "health id", "records", "डिजिटल"],
        "eligibility": "All Indian citizens",
        "citation": "ABDM: 'Every citizen can create a 14-digit ABHA number for digital health records.'",
        "benefits": "Free digital health ID + unified health records",
        "reasoningHi": "मुफ्त डिजिटल स्वास्थ्य ID और एकीकृत स्वास्थ्य रिकॉर्ड।",
        "documents": ["Aadhaar"],
        "steps": ["Visit abdm.gov.in", "Create ABHA number", "Link health records", "Access anywhere"],
        "deadline": "Always open",
        "link": "https://abdm.gov.in"
    },
    {
        "id": "aids-control",
        "name": "National AIDS & STD Control Programme",
        "nameHi": "राष्ट्रीय एड्स और STD नियंत्रण कार्यक्रम",
        "category": "Health",
        "state": "Central",
        "keywords": ["AIDS", "HIV", "STD", "testing", "treatment", "एड्स"],
        "eligibility": "All citizens — free HIV testing and ART treatment",
        "citation": "NACP: 'Free, voluntary, and confidential HIV testing and ART for all.'",
        "benefits": "Free HIV testing + ART treatment + counselling",
        "reasoningHi": "मुफ्त HIV परीक्षण और ART उपचार।",
        "documents": ["Aadhaar (optional)"],
        "steps": ["Visit nearest ICTC/ART centre", "Get tested (voluntary)", "Receive free ART if positive"],
        "deadline": "Always available",
        "link": "https://naco.gov.in"
    },
    {
        "id": "pm-rahat",
        "name": "PM RAHAT Scheme",
        "nameHi": "PM राहत योजना",
        "category": "Health",
        "state": "Central",
        "keywords": ["emergency", "accident", "trauma", "treatment", "दुर्घटना", "आपातकाल"],
        "eligibility": "Accident and trauma victims requiring emergency care",
        "citation": "PM RAHAT: 'Cashless emergency treatment for road accident victims during golden hour.'",
        "benefits": "Cashless treatment for accident victims up to ₹2.5 lakh",
        "reasoningHi": "दुर्घटना पीड़ितों को ₹2.5 लाख तक कैशलेस इलाज।",
        "documents": ["Aadhaar (if available)", "Police Report"],
        "steps": ["Taken to nearest empaneled hospital", "Treatment starts immediately", "No payment needed during golden hour"],
        "deadline": "Emergency — always",
        "link": "https://main.mohfw.gov.in"
    },
    {
        "id": "bio-pharma",
        "name": "Bio Pharma Shakti Initiative",
        "nameHi": "बायो फार्मा शक्ति पहल",
        "category": "Health",
        "state": "Central",
        "keywords": ["pharma", "biotech", "research", "vaccine", "manufacturing"],
        "eligibility": "Pharma/biotech companies and researchers",
        "citation": "Bio Pharma Shakti: 'Support for domestic vaccine and bio-pharma manufacturing.'",
        "benefits": "R&D grants and manufacturing support",
        "reasoningHi": "घरेलू वैक्सीन और बायो-फार्मा निर्माण को सहायता।",
        "documents": ["Company Registration", "Project Proposal"],
        "steps": ["Submit proposal to DBT", "Review and approval", "Funding disbursed"],
        "deadline": "As per call for proposals",
        "link": "https://dbtindia.gov.in"
    },
    {
        "id": "trauma-expansion",
        "name": "Emergency & Trauma Care Expansion",
        "nameHi": "आपातकालीन और ट्रॉमा देखभाल विस्तार",
        "category": "Health",
        "state": "Central",
        "keywords": ["emergency", "trauma", "ambulance", "hospital", "accident"],
        "eligibility": "All citizens needing emergency care",
        "citation": "MoHFW: 'Expansion of trauma care facilities along national highways and urban centres.'",
        "benefits": "Better emergency care infrastructure nationwide",
        "reasoningHi": "राष्ट्रीय राजमार्गों पर बेहतर आपातकालीन देखभाल सुविधाएँ।",
        "documents": [],
        "steps": ["Dial 108 or 112 for emergency", "Nearest trauma centre activated"],
        "deadline": "Always — emergency",
        "link": "https://main.mohfw.gov.in"
    },

    # ===== AGRICULTURE (10) =====
    {
        "id": "pm-kisan",
        "name": "PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)",
        "nameHi": "पीएम-किसान (प्रधानमंत्री किसान सम्मान निधि)",
        "category": "Agriculture",
        "state": "Central",
        "keywords": ["farmer", "kisan", "land", "agriculture", "farming", "किसान", "खेती", "कृषि", "जमीन"],
        "eligibility": "All land-holding farmer families, income below ₹2 lakh",
        "citation": "PM-KISAN Guidelines, Section 3.1: 'All land-holding farmer families with cultivable land are eligible. Family income shall not exceed ₹2,00,000 per annum.'",
        "benefits": "₹6,000/year in 3 installments of ₹2,000",
        "reasoningHi": "भूमि धारक किसान परिवारों को वार्षिक ₹6,000।",
        "documents": ["Aadhaar", "Land Records", "Bank Account"],
        "steps": ["Register at pmkisan.gov.in or CSC", "Submit Aadhaar + land records", "State verification", "₹2,000 every 4 months"],
        "deadline": "Rolling enrollment",
        "link": "https://pmkisan.gov.in"
    },
    {
        "id": "pmfby",
        "name": "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
        "nameHi": "प्रधानमंत्री फसल बीमा योजना (PMFBY)",
        "category": "Agriculture",
        "state": "Central",
        "keywords": ["farmer", "crop", "insurance", "farming", "bima", "loss", "किसान", "फसल", "बीमा"],
        "eligibility": "All farmers including sharecroppers, income below ₹1,50,000 for full subsidy",
        "citation": "PMFBY Guidelines 2023, Section 2.2: 'All farmers including sharecroppers growing notified crops are eligible. For full premium subsidy, annual income should not exceed ₹1,50,000.'",
        "benefits": "Crop insurance with 98% premium subsidy",
        "reasoningHi": "फसल बीमा, प्रीमियम पर 98% तक सब्सिडी।",
        "documents": ["Aadhaar", "Land Records", "Sowing Certificate", "Bank Account"],
        "steps": ["Contact bank/CSC before sowing", "Fill insurance form", "Pay 2% Kharif / 1.5% Rabi premium", "File claim if crop loss"],
        "deadline": "Kharif: July 31, Rabi: Dec 31",
        "link": "https://pmfby.gov.in"
    },
    {
        "id": "pmksy",
        "name": "PM Krishi Sinchai Yojana (PMKSY)",
        "nameHi": "PM कृषि सिंचाई योजना (PMKSY)",
        "category": "Agriculture",
        "state": "Central",
        "keywords": ["irrigation", "water", "farming", "drip", "sprinkler", "किसान", "सिंचाई"],
        "eligibility": "Farmers seeking micro-irrigation (drip/sprinkler)",
        "citation": "PMKSY: 'All farmers are eligible for micro-irrigation subsidies under Har Khet Ko Pani.'",
        "benefits": "55-75% subsidy on micro-irrigation systems",
        "reasoningHi": "माइक्रो-सिंचाई प्रणालियों पर 55-75% सब्सिडी।",
        "documents": ["Aadhaar", "Land Records", "Bank Account"],
        "steps": ["Apply at district agriculture office", "Select drip/sprinkler system", "Installation with subsidy", "Training provided"],
        "deadline": "Year-round",
        "link": "https://pmksy-mowr.nic.in"
    },
    {
        "id": "enam",
        "name": "e-NAM (National Agriculture Market)",
        "nameHi": "e-NAM (राष्ट्रीय कृषि बाज़ार)",
        "category": "Agriculture",
        "state": "Central",
        "keywords": ["market", "mandi", "sell", "crop", "price", "farmer", "किसान", "बाज़ार", "मंडी"],
        "eligibility": "All farmers and traders",
        "citation": "e-NAM: 'All farmers can sell produce online across state mandis for better prices.'",
        "benefits": "Online trading across 1,000+ mandis for best prices",
        "reasoningHi": "ऑनलाइन मंडी - बेहतर कीमत पर फसल बेचें।",
        "documents": ["Aadhaar", "Bank Account", "Produce Details"],
        "steps": ["Register at enam.gov.in", "List your produce", "Receive bids from traders", "Sell at best price"],
        "deadline": "Always open",
        "link": "https://enam.gov.in"
    },
    {
        "id": "rkvy",
        "name": "Rashtriya Krishi Vikas Yojana (RKVY)",
        "nameHi": "राष्ट्रीय कृषि विकास योजना (RKVY)",
        "category": "Agriculture",
        "state": "Central",
        "keywords": ["agriculture", "development", "farm", "innovation", "किसान", "कृषि"],
        "eligibility": "Farmers and agri-entrepreneurs",
        "citation": "RKVY-RAFTAAR: 'Support for agri-innovation, startups, and infrastructure development.'",
        "benefits": "Grants for agri-startups + infrastructure support",
        "reasoningHi": "कृषि-स्टार्टअप और बुनियादी ढांचे के लिए अनुदान।",
        "documents": ["Project Proposal", "Aadhaar", "Land Records"],
        "steps": ["Submit proposal to State Agriculture Dept", "Review and selection", "Funding released", "Implementation and monitoring"],
        "deadline": "As per state call",
        "link": "https://rkvy.nic.in"
    },
    {
        "id": "pkvy",
        "name": "Paramparagat Krishi Vikas Yojana (PKVY)",
        "nameHi": "परंपरागत कृषि विकास योजना (PKVY)",
        "category": "Agriculture",
        "state": "Central",
        "keywords": ["organic", "farming", "natural", "chemical-free", "किसान", "जैविक"],
        "eligibility": "Farmers interested in organic/natural farming",
        "citation": "PKVY: 'Clusters of 50 farmers in 50 acres can get organic farming support.'",
        "benefits": "₹50,000/hectare over 3 years for organic farming",
        "reasoningHi": "जैविक खेती के लिए ₹50,000/हेक्टेयर (3 वर्ष)।",
        "documents": ["Aadhaar", "Land Records", "Cluster Formation Details"],
        "steps": ["Form a cluster of 50 farmers", "Apply through district agriculture office", "Get certification", "Organic inputs + marketing support"],
        "deadline": "As per state notification",
        "link": "https://pkvydac.gov.in"
    },
    {
        "id": "soil-health",
        "name": "Soil Health Card Scheme",
        "nameHi": "मृदा स्वास्थ्य कार्ड योजना",
        "category": "Agriculture",
        "state": "Central",
        "keywords": ["soil", "health", "testing", "fertilizer", "farmer", "किसान", "मृदा"],
        "eligibility": "All farmers with cultivable land",
        "citation": "Soil Health Card: 'All farmers holding cultivable land are entitled to free soil testing every 2 years.'",
        "benefits": "Free soil testing + fertilizer recommendations",
        "reasoningHi": "मुफ्त मृदा परीक्षण + उर्वरक सिफारिशें।",
        "documents": ["Aadhaar", "Land Records"],
        "steps": ["Contact Block Agriculture Officer", "Soil sample collected", "Card issued within 30 days", "Follow fertilizer recommendations"],
        "deadline": "Ongoing",
        "link": "https://soilhealth.dac.gov.in"
    },
    {
        "id": "nmsa",
        "name": "National Mission for Sustainable Agriculture (NMSA)",
        "nameHi": "राष्ट्रीय टिकाऊ कृषि मिशन (NMSA)",
        "category": "Agriculture",
        "state": "Central",
        "keywords": ["sustainable", "climate", "agriculture", "rainfed", "water", "किसान", "कृषि"],
        "eligibility": "Farmers in rainfed/climate-vulnerable areas",
        "citation": "NMSA: 'Support for climate-adaptive farming practices in vulnerable agricultural zones.'",
        "benefits": "Support for water harvesting, soil health, and climate-resilient seeds",
        "reasoningHi": "जल संचयन, मृदा स्वास्थ्य और जलवायु-अनुकूल बीजों के लिए सहायता।",
        "documents": ["Aadhaar", "Land Records"],
        "steps": ["Contact district agriculture department", "Assess farm's climate vulnerability", "Get appropriate support package"],
        "deadline": "Ongoing",
        "link": "https://nmsa.dac.gov.in"
    },
    {
        "id": "seednet",
        "name": "Seednet India Portal",
        "nameHi": "सीडनेट इंडिया पोर्टल",
        "category": "Agriculture",
        "state": "Central",
        "keywords": ["seed", "variety", "crop", "farmer", "किसान", "बीज"],
        "eligibility": "Farmers and seed producers",
        "citation": "Seednet India: 'Information on certified seed varieties, availability, and sources.'",
        "benefits": "Access to certified seed info + quality seed sources",
        "reasoningHi": "प्रमाणित बीज जानकारी और गुणवत्ता बीज स्रोत।",
        "documents": [],
        "steps": ["Visit seednet.gov.in", "Search for crop varieties", "Find nearest seed dealer", "Purchase certified seeds"],
        "deadline": "Always available",
        "link": "https://seednet.gov.in"
    },
    {
        "id": "agmarknet",
        "name": "AGMARKNET",
        "nameHi": "AGMARKNET",
        "category": "Agriculture",
        "state": "Central",
        "keywords": ["market", "price", "mandi", "commodity", "farmer", "किसान", "बाज़ार"],
        "eligibility": "All farmers and traders",
        "citation": "AGMARKNET: 'Daily market prices of agricultural commodities across 7,000+ mandis.'",
        "benefits": "Real-time market prices to get best deal for produce",
        "reasoningHi": "7,000+ मंडियों में दैनिक बाज़ार मूल्य।",
        "documents": [],
        "steps": ["Visit agmarknet.gov.in", "Select commodity and market", "Check daily prices", "Decide best time to sell"],
        "deadline": "Always available",
        "link": "https://agmarknet.gov.in"
    },

    # ===== STATE-SPECIFIC (Gujarat) - For Conflict Demo =====
    {
        "id": "gujarat-kisan",
        "name": "Gujarat Kisan Sahay Yojana",
        "nameHi": "गुजरात किसान सहाय योजना",
        "category": "Agriculture",
        "state": "Gujarat",
        "keywords": ["farmer", "gujarat", "kisan", "crop", "loss", "किसान", "गुजरात"],
        "eligibility": "Gujarat farmers with 1-5 acres, income below ₹2,00,000",
        "citation": "Gujarat Kisan Sahay 2023, Section 4: 'Farmers with 1 to 5 acres and income below ₹2,00,000 are eligible. Minimum 1 acre holding required.'",
        "benefits": "₹20,000/hectare for crop loss, up to 4 hectares",
        "reasoningHi": "फसल नुकसान पर ₹20,000/हेक्टेयर, 4 हेक्टेयर तक।",
        "documents": ["Aadhaar", "7/12 Land Extract", "Income Certificate", "Bank Account"],
        "steps": ["Register on Digital Gujarat", "Submit land + income proof", "Taluka verification", "Compensation in 15 days"],
        "deadline": "Within 48 hours of calamity notification",
        "link": "https://digitalgujarat.gov.in"
    },
]


def get_schemes_by_category(category):
    return [s for s in SCHEMES if s["category"].lower() == category.lower()]


def search_schemes(query):
    query = query.lower()
    return [s for s in SCHEMES if any(kw in query for kw in s.get("keywords", []))]
