import { useParams, useNavigate } from 'react-router-dom'
import { useApp } from '../context/AppContext'
import { motion } from 'framer-motion'
import { ArrowLeft, FileText, ExternalLink, CheckCircle2, Clock, MapPin, Download, Printer } from 'lucide-react'

export default function SchemeDetail() {
  const { id } = useParams()
  const navigate = useNavigate()
  const { matchedSchemes, language } = useApp()
  const isHindi = language === 'hi'

  const scheme = matchedSchemes.find(s => s.id === id)

  if (!scheme) {
    return (
      <div className="min-h-screen pt-16 flex items-center justify-center">
        <div className="text-center">
          <p className="text-[var(--color-on-surface-variant)] mb-4">Scheme not found</p>
          <button onClick={() => navigate('/results')} className="px-6 py-3 bg-[var(--color-accent)] text-white rounded-xl font-semibold">
            Back to Results
          </button>
        </div>
      </div>
    )
  }

  // Mock form fields for auto-fill demo
  const formFields = [
    { label: 'Full Name', value: 'Ramesh Kumar Patel', source: 'Aadhaar Card' },
    { label: 'Age', value: '45', source: 'Aadhaar Card' },
    { label: 'Aadhaar Number', value: 'XXXX-XXXX-7834', source: 'Aadhaar Card' },
    { label: 'State', value: 'Gujarat', source: 'User Input' },
    { label: 'District', value: 'Mehsana', source: 'Aadhaar Card' },
    { label: 'Annual Income', value: '₹1,40,000', source: 'Income Certificate' },
    { label: 'Land Holding', value: '2 Acres', source: 'User Input' },
    { label: 'Bank Account', value: 'SBI - XXXXXX4521', source: 'Manual Entry' },
  ]

  const handleDownload = () => {
    const content = [
      `GOVERNMENT OF INDIA`,
      `${scheme.name}`,
      `Application Form (Draft)`,
      `Generated by PolicyPilot`,
      `Date: ${new Date().toLocaleDateString()}`,
      ``,
      `--- APPLICANT DETAILS ---`,
      ...formFields.map(f => `${f.label}: ${f.value} (Source: ${f.source})`),
      ``,
      `--- SCHEME DETAILS ---`,
      `Category: ${scheme.category}`,
      `Match: ${scheme.matchPercentage}%`,
      `Benefits: ${scheme.benefits}`,
      ``,
      `--- ELIGIBILITY REASONING ---`,
      scheme.reasoning,
      ``,
      `--- CITATION ---`,
      scheme.citation,
    ].join('\n')

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${scheme.name.replace(/\s+/g, '_')}_Application.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const handlePrint = () => {
    window.print()
  }

  return (
    <div className="min-h-screen pt-16 bg-[var(--color-surface)]">
      <div className="max-w-5xl mx-auto px-6 py-10">
        {/* Back Button */}
        <button onClick={() => navigate('/results')} className="flex items-center gap-2 text-sm text-[var(--color-on-surface-variant)] hover:text-[var(--color-accent)] mb-6 transition-colors">
          <ArrowLeft size={16} />
          {isHindi ? 'वापस परिणामों पर' : 'Back to Results'}
        </button>

        {/* Scheme Header */}
        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="mb-8">
          <div className="flex items-center gap-3 mb-2">
            <span className="text-xs font-semibold uppercase tracking-wider px-2 py-0.5 rounded-full bg-[var(--color-accent-container)] text-[var(--color-accent)]">
              {scheme.category}
            </span>
            <span className="text-xs font-bold text-[var(--color-success)]">{scheme.matchPercentage}% match</span>
          </div>
          <h1 className="text-2xl md:text-3xl font-bold text-[var(--color-on-surface)] mb-2">
            {isHindi ? scheme.nameHi : scheme.name}
          </h1>
          <p className="text-[var(--color-accent)] font-semibold">{scheme.benefits}</p>
          {scheme.link && (
            <a href={`https://www.google.com/search?q=${encodeURIComponent(scheme.name + ' official website india.gov.in')}`} target="_blank" rel="noopener noreferrer"
              className="inline-flex items-center gap-1 text-sm text-[var(--color-primary)] hover:underline mt-2">
              <ExternalLink size={12} /> {isHindi ? 'आधिकारिक वेबसाइट' : 'Official Website'}
            </a>
          )}
        </motion.div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Left Column - Checklist + Steps */}
          <div className="lg:col-span-2 space-y-6">
            {/* Eligibility Reasoning */}
            <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
              className="bg-[var(--color-surface-container-lowest)] rounded-xl p-6 shadow-[var(--shadow-sm)]">
              <h2 className="text-sm font-bold uppercase tracking-wider text-[var(--color-on-surface-variant)] mb-3">
                {isHindi ? 'पात्रता विवरण' : 'Eligibility Reasoning'}
              </h2>
              <p className="text-[var(--color-on-surface)] leading-relaxed mb-4">
                {isHindi ? scheme.reasoningHi : scheme.reasoning}
              </p>
              <div className="p-4 bg-[var(--color-surface-container-low)] rounded-lg">
                <div className="flex items-start gap-2">
                  <FileText size={14} className="text-[var(--color-primary)] mt-0.5 shrink-0" />
                  <div>
                    <span className="citation-badge mb-1">PDF Source</span>
                    <p className="text-xs text-[var(--color-on-surface-variant)] mt-1 italic leading-relaxed">
                      "{scheme.citation}"
                    </p>
                  </div>
                </div>
              </div>
            </motion.div>

            {/* Step-by-Step Checklist */}
            <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}
              className="bg-[var(--color-surface-container-lowest)] rounded-xl p-6 shadow-[var(--shadow-sm)]">
              <h2 className="text-sm font-bold uppercase tracking-wider text-[var(--color-on-surface-variant)] mb-4">
                {isHindi ? 'आवेदन चरण' : 'Application Steps'}
              </h2>
              <div className="space-y-4">
                {scheme.steps.map((step, i) => (
                  <div key={i} className="flex items-start gap-4">
                    <div className="w-8 h-8 rounded-full bg-[var(--color-accent)] text-white flex items-center justify-center text-sm font-bold shrink-0">
                      {i + 1}
                    </div>
                    <div className="flex-1 pt-1">
                      <p className="text-sm text-[var(--color-on-surface)]">{step}</p>
                    </div>
                  </div>
                ))}
              </div>

              {/* Deadline */}
              <div className="mt-6 pt-4 border-t border-[var(--color-outline-variant)]/20 flex items-center gap-2">
                <Clock size={14} className="text-[var(--color-warning)]" />
                <span className="text-sm text-[var(--color-on-surface-variant)]">
                  <strong>{isHindi ? 'समय सीमा:' : 'Deadline:'}</strong> {scheme.deadline}
                </span>
              </div>
            </motion.div>

            {/* Auto-filled Form */}
            <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}
              className="bg-[var(--color-surface-container-lowest)] rounded-xl p-6 shadow-[var(--shadow-sm)]">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-sm font-bold uppercase tracking-wider text-[var(--color-on-surface-variant)]">
                  {isHindi ? 'स्वतः भरा हुआ आवेदन पत्र' : 'Auto-Filled Application Form'}
                </h2>
                <div className="flex gap-2">
                  <button onClick={handleDownload} className="flex items-center gap-1 text-xs px-3 py-1.5 rounded-lg bg-[var(--color-surface-container-low)] text-[var(--color-on-surface-variant)] hover:bg-[var(--color-surface-container-high)] transition-colors">
                    <Download size={12} /> {isHindi ? 'डाउनलोड' : 'Download'}
                  </button>
                  <button onClick={handlePrint} className="flex items-center gap-1 text-xs px-3 py-1.5 rounded-lg bg-[var(--color-surface-container-low)] text-[var(--color-on-surface-variant)] hover:bg-[var(--color-surface-container-high)] transition-colors">
                    <Printer size={12} /> {isHindi ? 'प्रिंट' : 'Print'}
                  </button>
                </div>
              </div>

              <div className="bg-[var(--color-surface)] border border-[var(--color-outline-variant)]/30 rounded-xl p-6">
                <div className="text-center mb-6 pb-4 border-b border-[var(--color-outline-variant)]/20">
                  <p className="text-xs text-[var(--color-outline)] uppercase tracking-widest">Government of India</p>
                  <h3 className="font-bold text-[var(--color-on-surface)]">{scheme.name}</h3>
                  <p className="text-xs text-[var(--color-outline)]">Application Form (Draft)</p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {formFields.map((field, i) => (
                    <div key={i}>
                      <label className="block text-xs uppercase tracking-wider text-[var(--color-on-surface-variant)] mb-1 font-semibold">
                        {field.label}
                      </label>
                      <div className="flex items-center gap-2">
                        <input
                          type="text"
                          defaultValue={field.value}
                          className="quiet-input text-sm"
                        />
                        {field.source !== 'Manual Entry' && (
                          <span className="text-[0.6rem] px-1.5 py-0.5 rounded bg-[var(--color-success-container)] text-[var(--color-success)] font-medium whitespace-nowrap">
                            {field.source}
                          </span>
                        )}
                      </div>
                    </div>
                  ))}
                </div>

                <div className="mt-6 pt-4 border-t border-[var(--color-outline-variant)]/20">
                  <p className="text-xs text-[var(--color-outline)] flex items-center gap-1">
                    <CheckCircle2 size={12} className="text-[var(--color-success)]" />
                    {isHindi
                      ? '6 में से 6 फ़ील्ड आपके दस्तावेज़ों से स्वतः भरे गए'
                      : '6 of 8 fields auto-filled from your uploaded documents'}
                  </p>
                </div>
              </div>
            </motion.div>
          </div>

          {/* Right Column - Citation Sidebar */}
          <div className="space-y-6">
            {/* Documents Required */}
            <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }}
              className="bg-[var(--color-surface-container-lowest)] rounded-xl p-5 shadow-[var(--shadow-sm)]">
              <h3 className="text-xs font-bold uppercase tracking-wider text-[var(--color-on-surface-variant)] mb-3">
                {isHindi ? 'आवश्यक दस्तावेज़' : 'Documents Required'}
              </h3>
              <ul className="space-y-2">
                {scheme.documents.map((doc, i) => (
                  <li key={i} className="flex items-center gap-2 text-sm text-[var(--color-on-surface)]">
                    <CheckCircle2 size={14} className="text-[var(--color-success)] shrink-0" />
                    {doc}
                  </li>
                ))}
              </ul>
            </motion.div>

            {/* Source Citation */}
            <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.25 }}
              className="bg-[var(--color-primary)] rounded-xl p-5 text-white">
              <h3 className="text-xs font-bold uppercase tracking-wider text-white/70 mb-3">
                {isHindi ? 'PDF स्रोत' : 'PDF Source Citation'}
              </h3>
              <p className="text-xs leading-relaxed text-white/80 italic">
                "{scheme.citation}"
              </p>
              <div className="mt-3 pt-3 border-t border-white/10">
                <span className="text-[0.6rem] uppercase tracking-widest text-white/50">
                  {isHindi ? 'सत्यापित स्रोत • सरकारी PDF' : 'Verified Source • Official PDF'}
                </span>
              </div>
            </motion.div>

            {/* Quick Actions */}
            <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.35 }}
              className="bg-[var(--color-surface-container-lowest)] rounded-xl p-5 shadow-[var(--shadow-sm)]">
              <h3 className="text-xs font-bold uppercase tracking-wider text-[var(--color-on-surface-variant)] mb-3">
                {isHindi ? 'त्वरित कार्रवाई' : 'Quick Actions'}
              </h3>
              <div className="space-y-2">
                {scheme.link && (
                  <a href={`https://www.google.com/search?q=${encodeURIComponent(scheme.name + ' official website apply online')}`} target="_blank" rel="noopener noreferrer"
                    className="flex items-center gap-2 text-sm text-[var(--color-accent)] hover:underline">
                    <ExternalLink size={14} /> {isHindi ? 'आधिकारिक वेबसाइट खोलें' : 'Visit Official Website'}
                  </a>
                )}
                <a href={`https://www.google.com/maps/search/${encodeURIComponent(scheme.category + ' government office near me')}`} target="_blank" rel="noopener noreferrer"
                  className="flex items-center gap-2 text-sm text-[var(--color-accent)] hover:underline">
                  <MapPin size={14} /> {isHindi ? 'नज़दीकी कार्यालय खोजें' : 'Find Nearest Office'}
                </a>
              </div>
            </motion.div>
          </div>
        </div>
      </div>
    </div>
  )
}
